projects:
  epicmealtime:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: wrlare5bl5hhjdee43dyge37ke
      endpoints:
        prod: >-
          https://bolyytba2zgwliyju56d5tz3ru.appsync-api.eu-west-1.amazonaws.com/graphql
